### ISSUE TITLE
Implement regex

### ISSUE THREAD

**Issue by yauangon** [ngoccuongpvc/SCFC#39]

**Comment by FinisTP** [comment]
ID các thứ, username, password, class, lecturer account, room, class name -> tự do nhưng ko có khoảng cách
start day, end day: DD/MM/YYYY
start hour, end hour: HH:MM
day + score: số
name(scoreboard): midterm/lab/final/bonus
gender: male/female/bede
dob: DD/MM/YYYY
semester: spring/summer/fall/winter
year: 20XX-20YY
last name, first name, course name: tự do
ALL: KHÔNG CÓ DẤU PHẨY, NHẬP VÀO DATABASE PHẢI LOWERCASE HẾT

**Comment by FinisTP** [comment]
year + dob: YYYY/MM/DD (theo đề bài)

**Comment by FinisTP** [comment]
day: 1-10

**Comment by yauangon** [comment]
Done

**Comment by yauangon** [comment]
> day: 1-10

Hiện tại restricted thành day: 00-99 (hai chữ số)
